### ISSUE TITLE
GUI로 어떻게 만들까요???

### ISSUE THREAD

**Issue by Anger27** [Anger27/jsmpeg-vnc#3]
GUI로 어떻게 만들까요???

**Comment by passionsjin** [comment]
# GUI로 jsmpeg-vnc가 실행 되도록 하면 되겠는데
* 흠....

**Comment by Anger27** [comment]
그럼 자바 같은걸로 cmd 쓰는 법이 있을까요?

**Comment by passionsjin** [comment]
찾아보니까 runtime 클래스 쓰면 된다는데??
> http://www.specialguy.net/87

**Comment by passionsjin** [comment]
# 우선 GUI는 빨리 만드니까 GUI 만들어보자
