### ISSUE TITLE
GUI 만들어봤는데 어떤지 의견 말해주기 바람.

### ISSUE THREAD

**Issue by passionsjin** [Anger27/jsmpeg-vnc#4]
* 필요한거만 넣었음.
*

**Comment by Anger27** [comment]
편의성을 위한거면 기타 설정을 메인 폼에 넣지 말고 걍 디폴트값으로 두고 따로 고급 설정 버튼을 만들어서 새폼을 만드는게 좋을거 같아요.

**Comment by Anger27** [comment]
평상시에는 디폴트로 고급설정 시 버튼을 눌러서 새로운 창이 뜨게 하고 거기서 고급설정을 하는거죠

**Comment by jhyun3728** [comment]
왜 나는 알집으로 잡히는거지?

**Comment by jhyun3728** [comment]
## 해결!

**Comment by passionsjin** [comment]
커밋함
