### ISSUE TITLE
vnc 접속시 로그인 기능

### ISSUE THREAD

**Issue by Anger27** [Anger27/jsmpeg-vnc#7]
vnc 접속시 프로프트로 패스워드 입력을 받는 기능을 커밋했는데 
<script>------1
로그인 기능
<script>vnc시작</script>--------2
<script>vnc시작</script>--------3
</script>--------4
이렇게 작성하니 1블록이 4로 닫기는게 아니라 2로 닫기게 되네요.
혹시 다른 방법이 있을까요??

**Comment by passionsjin** [comment]
index.html 에서 index2.html 넘기는 방법으로 해도 안된다 큰일..
